pipeline{
    agent any

    environment{
        RELEASE = '0.0.1'
    }

    stages{
        stage('build'){
           environment{
            LOG_LEVEL = 'info'
           }

            steps{
                echo "Building release ${RELEASE} with log level ${LOG_LEVEL} ...."
            }
        }
        stage('Test'){
            steps{
                echo "Testing. In can see release ${RELEASE}, but not log level"
            }
        }
        stage('Deploy'){
            input{
                message 'Deploy? '
                ok 'Do it'
                parameters{
                    string(name: 'TARGET_ENVIRONMENT', defaultValue: 'PROD', description: 'Target deployment environmeent')
                }
            }
            steps{
                echo "Deployment release ${RELEASE} to ${TARGET_ENVIRONMENT}"
            }
        }
    }
}