library identifier: 'jenkins-session-library@main', retriever: modernSCM([$class: 'GitSCMSource', remote:'https://github.com/LuisGarridoOgalla/jenkins-session-library.git'])
pipeline{
    agent any

    stages{
        stage('Audit tools'){
            steps{
                auditTools()
            }
        }
        
    }    
}
