library identifier: 'jenkins-session-library@main', rerriever: modernSMC([$class: 'GitSMCSource', remote:'https://github.com/LuisGarridoOgalla/jenkins-session-library.git'])
pipeline{
    agent any

    stages{
        stage('Audit tools'){
            steps{
                auditTool()
            }
        }
        
    }    
}
